openapi: 3.0.3
info:
  $ref: "info.yml"
servers:
  - url: /
tags:
  $ref: "tags.yml"
security:
  - OauthToken: []
    OauthSecret: []
  - ConsumerKey: []
    ConsumerSecret: []
paths:
  $ref: "paths/index.yml"
components:
  securitySchemes:
    ConsumerKey:
      type: apiKey
      in: header
      name: consumer-key
    ConsumerSecret:
      type: apiKey
      in: header
      name: consumer-secret
    OauthToken:
      type: apiKey
      in: header
      name: oauth-token
    OauthSecret:
      type: apiKey
      in: header
      name: oauth-secret
